[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
BACKEND_PORT = "8000"
FRONTEND_PORT = "3000"
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://salary-predictor-production.up.railway.app"
