[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
BACKEND_PORT = "8000"
FRONTEND_PORT = "3000"
NODE_ENV = "production"
