[[services]]
name = "backend"
dockerfile = "Dockerfile"
internal_port = 8000
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[services.env]
PYTHON_VERSION = "3.12"
PORT = "8000"

[[services]]
name = "frontend"
dockerfile = "Dockerfile"
root_directory = "frontend"
internal_port = 3000
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[services.env]
NODE_ENV = "production"
PORT = "3000"
NEXT_PUBLIC_API_URL = "${RAILWAY_SERVICE_BACKEND_URL}"
